# NumPy

This shall give you an idea of the intricacies in this library and will make you appreciate why NumPy is soo useful. 

In [1]:
import numpy as np

## Vectorization

NumPy vectorization involves performing mathematical operations on entire
arrays, eliminating the need to loop through individual elements.

Let's compare the execution times of a non-vectorized program and a vectorized one.

Your goal is to multiply each element of the 2D arrays by 3. Implement this using both non-vectorized and vectorized approaches.



In [ ]:
import time

arr_nonvectorized = np.random.rand(1000, 1000)
arr_vectorized = np.array(arr_nonvectorized) # making a deep copy of the array https://stackoverflow.com/questions/184710/what-is-the-difference-between-a-deep-copy-and-a-shallow-copy

start_nv = time.time()

# Non-vectorized approach
# <START>

# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000*(end_nv-start_nv), "ms")

start_v = time.time()

# Vectorized approach
# <START>

# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000*(end_v-start_v), "ms")

# uncomment and execute the below line to convince yourself that both approaches are doing the same thing
# print(np.allclose(arr_nonvectorized, arr_vectorized))

Time taken in non-vectorized approach: 603.1436920166016 ms
Time taken in vectorized approach: 4.992485046386719 ms


Perform Matrix Multiplication of A and B using vectorized and non-vectorized means and observe the time difference.

In [ ]:
# Generate two random 500x500 matrices
A = np.random.rand(500, 500)
B = np.random.rand(500, 500)

# Non-vectorized matrix multiplication
C_nonvectorized = np.zeros((500, 500))  # Initialize result matrix
start_nv = time.time()

# <START: Non-vectorized approach>

# <END>

end_nv = time.time()
print("Time taken in non-vectorized approach:", 1000 * (end_nv - start_nv), "ms")

# Vectorized matrix multiplication
start_v = time.time()

# <START: Vectorized approach>

# <END>

end_v = time.time()
print("Time taken in vectorized approach:", 1000 * (end_v - start_v), "ms")

# Uncomment and execute the below line to verify both approaches give the same result
# print(np.allclose(C_nonvectorized, C_vectorized))

Time taken in non-vectorized approach: 99469.41924095154 ms
Time taken in vectorized approach: 148.118257522583 ms


Vectorization uses NuPy's low level operations to speed things up. Make sure you know why!

### :\\/: *no for loops alllowed  hereafter* :\\/:

## Broadcasting

You are given a set of 5 2D points as an ndarray and you want to compute the euclidean distance between each pair of points and store it into a 5*5 ndarray.

*Hint: use the* `np.linalg.norm()` *function for this*

In [ ]:
import numpy as np

# Generate a random 5x2 array of points (values between 0 and 10)
points = np.random.rand(5, 2) * 10
print("2D Points:\n", points)

# Task: Compute pairwise Euclidean distances using broadcasting
# <START: Pairwise distance computation>
distance_matrix = None # Replace with broadcasting operation
# <END>

#  Print the distance matrix
print("Pairwise Euclidean Distance Matrix:\n", distance_matrix)


2D Points:
 [[2.82292798 5.40822838]
 [1.75029328 3.17478992]
 [1.09855607 6.94539021]
 [9.43407364 5.92061512]
 [7.45620999 0.18868497]]
[[0.         2.47765868 2.3100487  6.63097181 6.97932201]
 [2.47765868 0.         3.8265112  8.1596591  6.440055  ]
 [2.3100487  3.8265112  0.         8.39827465 9.27754435]
 [6.63097181 8.1596591  8.39827465 0.         6.06357714]
 [6.97932201 6.440055   9.27754435 6.06357714 0.        ]]
Pairwise Euclidean Distance Matrix:
 [[ 0.          3.58849876  1.48347875  0.6202771   6.97327213]
 [ 3.58849876  0.          5.07197003  2.98331895 10.20051406]
 [ 1.48347875  5.07197003  0.          2.0945745   5.76886337]
 [ 0.6202771   2.98331895  2.0945745   0.          7.55828466]
 [ 6.97327213 10.20051406  5.76886337  7.55828466  0.        ]]


In [18]:
# 2 x 5 x 5
(9.71911312 - 4.1080346)**2 + (6.53592428-5.63094852)**2

32.30318328379296

## 